package server

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"math/big"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// llm_generate_gateway_route_test.go — routing regression guard for
// HXC-002-F3-03 (gap ledger docs/qa/2026-09-05-gap-ledger.md): the HelixLLM
// gateway route resolveLLMProvider adds (internal/server/llm_generate.go)
// alongside the pre-existing local-coder route.
//
// Verified facts:
//   - Gateway: https://127.0.0.1:8443/v1, self-signed TLS.
//   - resolveLLMProvider registers the selector names "gateway" /
//     "helixllm-gateway" and dispatches them to
//     resolveHelixLLMGatewayProvider.
//   - The PRE-EXISTING coder check is
//     `strings.EqualFold(requested, "helixllm") || strings.EqualFold(requested, "local")`
//     — an EXACT, case-insensitive match, not a substring/prefix test. The
//     ordering hazard this guard exists to catch: if the gateway match is ever
//     rewritten as a loose test (e.g.
//     strings.Contains(strings.ToLower(requested), "helixllm")) instead of an
//     exact match, OR if it is registered AFTER a loosened pre-existing check,
//     "helixllm-gateway" would be silently swallowed by the coder branch and
//     routed to the WRONG endpoint.
//
// SELF-CONTAINED CA (why this file mints its own certificate). The gateway
// route resolves its trust anchor via envHelixLLMGatewayCACert(), which falls
// back to walking up the tree for the in-repo
// submodules/helix_llm/certs/cert.pem. That file is NOT tracked —
// submodules/helix_llm/.gitignore carries `*.pem`, and `git ls-files certs/`
// returns only README.md, which documents the certificate as REGENERATED by
// `make certs`. llm.NewOpenAICompatibleProvider reads the CA at CONSTRUCTION
// time, so on any checkout where nobody has run `make certs` the resolver
// returns its "CA certificate could not be located" error and the gateway
// subtests hit t.Fatalf — a hard FAIL contingent purely on operator machine
// state (§11.4.50 determinism defect). These subtests are about ROUTING, not
// trust, and the constructor performs NO network I/O, so the fix is to remove
// the environment dependency entirely: mint an ephemeral self-signed
// certificate into t.TempDir() and point HELIX_LLM_GATEWAY_CA_CERT at it.
// Skipping when the repo certificate is absent was REJECTED: that would
// silently stop guarding the route on exactly the machines most likely to
// regress it (a fresh clone, a CI-less contributor checkout).
//
// Run:
//
//	cd helix_code && <toolchain> test -v -run TestResolveLLMProvider_GatewayRouteResolution ./internal/server/...
func TestResolveLLMProvider_GatewayRouteResolution(t *testing.T) {
	// Pin every higher-precedence/lower-precedence source so ONLY the
	// explicitly-passed providerName argument decides the route for each
	// subtest — matches the isolation discipline
	// TestResolveLLMProvider_ConfigDefaultLocalRoutesToCoder already
	// established in this package.
	t.Setenv("HELIX_LLM_PROVIDER", "")
	prevConfigDefault := configDefaultProviderFunc
	configDefaultProviderFunc = func() string { return "" }
	t.Cleanup(func() { configDefaultProviderFunc = prevConfigDefault })

	// Remove the untracked-in-repo-certificate dependency (see the file header).
	t.Setenv(helixLLMGatewayCACertEnv, writeEphemeralGatewayCACert(t))

	// Compare against the SAME normalisation production uses. Reading the raw
	// HELIX_LLM_GATEWAY_ENDPOINT value here (an earlier draft) diverged from
	// envHelixLLMGatewayEndpoint(), which appends "/v1" when absent — so an
	// operator with HELIX_LLM_GATEWAY_ENDPOINT=https://host:8443 exported made
	// this guard fail spuriously on a correctly-routed provider.
	gatewayWant := envHelixLLMGatewayEndpoint()
	coderWant := envHelixLLMLocalEndpoint()

	cases := []struct {
		name          string
		requested     string
		wantBaseURL   string
		isGatewayCase bool
	}{
		// Guard item 6 (§11.4.122 — the gateway is added ALONGSIDE the coder
		// route, never instead of it): these two subtests must keep passing
		// now that the gateway has landed.
		{name: "helixllm_still_routes_to_coder", requested: "helixllm", wantBaseURL: coderWant},
		{name: "local_still_routes_to_coder", requested: "local", wantBaseURL: coderWant},

		// Guard item 4 (route resolution): the gateway selector names.
		{name: "gateway_selector_routes_to_gateway", requested: "gateway", wantBaseURL: gatewayWant, isGatewayCase: true},
		{name: "helixllm-gateway_selector_routes_to_gateway", requested: "helixllm-gateway", wantBaseURL: gatewayWant, isGatewayCase: true},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			provider, err := resolveLLMProvider(tc.requested, "")
			if err != nil {
				if tc.isGatewayCase {
					t.Fatalf("resolveLLMProvider(%q, \"\") returned an error instead of "+
						"resolving to the gateway route (want base URL %q): %v",
						tc.requested, tc.wantBaseURL, err)
				}
				t.Fatalf("resolveLLMProvider(%q, \"\") failed: %v", tc.requested, err)
			}
			defer func() { _ = provider.Close() }()

			// Same BaseURL()-only type assertion
			// TestResolveLLMProvider_ConfigDefaultLocalRoutesToCoder uses —
			// deliberately generic so this guard does not need to import
			// internal/llm's concrete *OpenAICompatibleProvider type nor
			// assume which concrete type the gateway constructor returns.
			bu, ok := provider.(interface{ BaseURL() string })
			if !ok {
				t.Fatalf("provider for %q is %T, which does not expose BaseURL() — "+
					"cannot verify which endpoint it resolved to", tc.requested, provider)
			}
			if bu.BaseURL() != tc.wantBaseURL {
				t.Fatalf("resolveLLMProvider(%q, \"\").BaseURL() = %q, want %q — "+
					"this is exactly the ordering hazard this guard exists to catch: a "+
					"loose/substring gateway-name match (or a mis-ordered exact match) "+
					"can swallow one selector's traffic into the other route",
					tc.requested, bu.BaseURL(), tc.wantBaseURL)
			}
			t.Logf("PASS: resolveLLMProvider(%q, \"\") routed to BaseURL=%q", tc.requested, bu.BaseURL())
		})
	}
}

// writeEphemeralGatewayCACert mints a throwaway self-signed CA certificate into
// the test's own temporary directory and returns its path.
//
// It exists so the gateway ROUTING guards above never depend on an untracked
// file (submodules/helix_llm/certs/cert.pem, produced by `make certs`) being
// present on the machine running the suite. The certificate is never used to
// dial anything: llm.NewOpenAICompatibleProvider only needs the PEM to parse
// so it can build the client's trust pool
// (internal/llm/openai_compatible_provider.go newOpenAICompatibleHTTPClient),
// and the route guards assert only on the constructed provider's BaseURL().
// Nothing here weakens TLS verification anywhere: no InsecureSkipVerify, no
// change to the production trust path, and the key material lives for the
// duration of one test in a directory the testing package deletes.
func writeEphemeralGatewayCACert(t *testing.T) string {
	t.Helper()

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generating the ephemeral CA key failed: %v", err)
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		t.Fatalf("generating the ephemeral CA serial number failed: %v", err)
	}

	template := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "helixcode-test-ephemeral-ca"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		t.Fatalf("creating the ephemeral CA certificate failed: %v", err)
	}

	path := filepath.Join(t.TempDir(), "gateway-ephemeral-ca.pem")
	pemBytes := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	if pemBytes == nil {
		t.Fatal("PEM-encoding the ephemeral CA certificate produced no bytes")
	}
	if err := os.WriteFile(path, pemBytes, 0o600); err != nil {
		t.Fatalf("writing the ephemeral CA certificate to %s failed: %v", path, err)
	}
	return path
}

// TestProviderResolveStatus_ServerSideUnknownProviderIsNot4xx is the guard for
// the second review blocker: a provider name the SERVER's own configuration
// supplies — the config file's llm.default_provider, or the server process's
// HELIX_LLM_PROVIDER — that llm.Select cannot resolve was reported to the
// client as HTTP 400 "invalid request".
//
// It lives in this file because this file and internal/server/llm_generate.go
// are the two sources in scope for the review-remediation task; the assertion
// itself is about provider-resolution status mapping, not about the gateway
// route.
//
// Why it was wrong: the caller sent no `provider` field at all, so 400 blames
// them for a deployment fault they cannot see or fix, every request to that
// deployment fails identically, and providerResolveStatus's own doc-comment
// ("the caller typed an invalid provider name") became false. A Claude Code
// user saw "400 invalid request" for a server-side misconfiguration.
//
// The name pinned below need not even be a typo: parseCloudProviderType
// (internal/llm/provider_factory.go) deliberately rejects "vllm", "localai"
// and "lmstudio" on this path, so a config declaring one of those hit exactly
// this mis-attribution.
//
// §1.1 FALSIFYING MUTATION — the single edit that makes this test FAIL:
// in internal/server/llm_generate.go, collapse unknownProviderError's switch
// back to its pre-fix single form, i.e. replace the whole switch body with
//
//	return fmt.Errorf("%w: %q", errUnknownProvider, requested)
//
// Then the config- and env-sourced cases below produce errUnknownProvider,
// providerResolveStatus returns 400, and BOTH the "not a 4xx" and the
// "names the source key" assertions fail. (Mutating only providerResolveStatus
// — dropping its errServerProviderMisconfigured branch so the error falls
// through to 503 — also fails the test, on the exact-500 assertion.)
func TestProviderResolveStatus_ServerSideUnknownProviderIsNot4xx(t *testing.T) {
	const unresolvable = "definitely-not-a-real-provider-config-typo"

	t.Run("config_default_provider_is_a_server_fault", func(t *testing.T) {
		// Higher-precedence sources empty, so ONLY the config default can name
		// the provider (flag > env > config).
		t.Setenv("HELIX_LLM_PROVIDER", "")
		prev := configDefaultProviderFunc
		configDefaultProviderFunc = func() string { return unresolvable }
		t.Cleanup(func() { configDefaultProviderFunc = prev })

		provider, err := resolveLLMProvider("", "")
		if provider != nil {
			defer func() { _ = provider.Close() }()
		}
		if err == nil {
			t.Fatalf("resolveLLMProvider(\"\", \"\") with llm.default_provider=%q "+
				"returned no error — an unresolvable configured default must never "+
				"silently fall back to another backend", unresolvable)
		}

		if !errors.Is(err, errServerProviderMisconfigured) {
			t.Fatalf("error %v is not errServerProviderMisconfigured — a provider "+
				"name the request never supplied must be classified as a server "+
				"fault", err)
		}
		if errors.Is(err, errUnknownProvider) {
			t.Fatalf("error %v is still errUnknownProvider — that sentinel maps to "+
				"400 and blames the caller for the server's own configuration", err)
		}

		status := providerResolveStatus(err)
		if status >= 400 && status <= 499 {
			t.Fatalf("providerResolveStatus = %d (a 4xx) for a fault in the "+
				"server's own %s — the caller sent no provider and cannot fix this",
				status, configDefaultProviderKey)
		}
		if status != http.StatusInternalServerError {
			t.Fatalf("providerResolveStatus = %d, want %d: a deterministic "+
				"configuration fault no retry can clear must not be advertised as "+
				"the temporary/retryable 503", status, http.StatusInternalServerError)
		}

		msg := err.Error()
		if !strings.Contains(msg, configDefaultProviderKey) {
			t.Fatalf("error message %q does not name %q — an operator reading the "+
				"response has nothing pointing at the key they must correct",
				msg, configDefaultProviderKey)
		}
		if !strings.Contains(msg, unresolvable) {
			t.Fatalf("error message %q does not echo the unresolvable value %q",
				msg, unresolvable)
		}
		t.Logf("PASS: config-sourced unresolvable provider -> status %d, error %q", status, msg)
	})

	t.Run("env_helix_llm_provider_is_a_server_fault", func(t *testing.T) {
		// The same mis-attribution predates the config threading: a bad
		// HELIX_LLM_PROVIDER in the SERVER's environment is equally invisible
		// to the caller.
		t.Setenv("HELIX_LLM_PROVIDER", unresolvable)
		prev := configDefaultProviderFunc
		configDefaultProviderFunc = func() string { return "" }
		t.Cleanup(func() { configDefaultProviderFunc = prev })

		provider, err := resolveLLMProvider("", "")
		if provider != nil {
			defer func() { _ = provider.Close() }()
		}
		if err == nil {
			t.Fatalf("resolveLLMProvider(\"\", \"\") with %s=%q returned no error",
				llmProviderEnv, unresolvable)
		}
		if !errors.Is(err, errServerProviderMisconfigured) {
			t.Fatalf("error %v is not errServerProviderMisconfigured", err)
		}

		status := providerResolveStatus(err)
		if status >= 400 && status <= 499 {
			t.Fatalf("providerResolveStatus = %d (a 4xx) for a fault in the "+
				"server's own %s environment", status, llmProviderEnv)
		}
		if !strings.Contains(err.Error(), llmProviderEnv) {
			t.Fatalf("error message %q does not name %s", err.Error(), llmProviderEnv)
		}
		t.Logf("PASS: env-sourced unresolvable provider -> status %d, error %q", status, err.Error())
	})

	t.Run("caller_supplied_unknown_provider_is_still_400", func(t *testing.T) {
		// Non-regression: the existing, correct 400 for a name the CALLER
		// actually typed must survive the fix (server defect #4).
		t.Setenv("HELIX_LLM_PROVIDER", "")
		prev := configDefaultProviderFunc
		configDefaultProviderFunc = func() string { return "" }
		t.Cleanup(func() { configDefaultProviderFunc = prev })

		provider, err := resolveLLMProvider(unresolvable, "")
		if provider != nil {
			defer func() { _ = provider.Close() }()
		}
		if err == nil {
			t.Fatalf("resolveLLMProvider(%q, \"\") returned no error", unresolvable)
		}
		if !errors.Is(err, errUnknownProvider) {
			t.Fatalf("error %v is not errUnknownProvider — a caller-supplied bad "+
				"name must stay a client error", err)
		}
		if errors.Is(err, errServerProviderMisconfigured) {
			t.Fatalf("error %v was classified as a server fault, but the caller "+
				"supplied the name", err)
		}
		if status := providerResolveStatus(err); status != http.StatusBadRequest {
			t.Fatalf("providerResolveStatus = %d, want %d for a caller-supplied "+
				"unknown provider name", status, http.StatusBadRequest)
		}
		t.Logf("PASS: caller-supplied unknown provider -> status %d", http.StatusBadRequest)
	})
}
